### ISSUE TITLE
Naming variables with underscores causes inaccurate "Symbol Not In Scope" errors

### ISSUE THREAD

**Issue by zcmoore** [zcmoore/plp-grinder#11]
## Description

If the java source code includes identifiers that contain underscores (e.g. private int some_var), the compiler will complain the the identifier is not in scope, even if it should be.
## Predicted Cause

The symbol table may be delimiting scopes by underscore (_), when it should delimit scopes with period (.)
## Solution and Side Effects

Symbol table needs to delimit scopes by period (.)
Updating this will cause compile_method_body() to become inaccurate, as it currently extends namespaces with an underscore. Note that we should refactor compile_method_body() to not depend on the symbol table implementation. Perhaps a static method in SymbolTable called **get_extended_namespace(namespace: str, extension: str)** OR **concat_namespace(namespace: str, extension: str)**?

**Comment by zcmoore** [comment]
I'm reopening this issue on the following grounds:
BasicArithmatic.java fails to compile, as the variable "staticClassExample" cannot be found in the namespace "BasitcArithmatic_main"

Directly, this is because the namesapce should be "BasitcArithmatic.main" (notice the . instead of _ ). Indirectly, this is caused by the issues listed in Solution and Side Effects above.

compiler.rs needs to be updated to abide by the new conventions. Additionally, static functions should be used across all code (in the parser and in the compilation code) in order to remove the dependency of compiler.rs on the implementation of the parser.

**Comment by MorganNesbitt** [comment]
it is BasicArithmatic.main when I run it.
When you run it, is the namespace not BasicArithmatic.main

**Comment by zcmoore** [comment]
When I run it, I get the following error. Are you not experiencing this on your end?
![Compile Error](http://puu.sh/j2LbM/55fdfc7232.jpg)

As you can see, compiler.rs is searching the namespace "BasicArithmatic_main" when it should be searching "Basic Arithmatic.main"

**Comment by MorganNesbitt** [comment]
I am but you stated "Directly, this is because the namesapce should be "BasitcArithmatic.main" (notice the . instead of _ ). " and when i run it, in symbols_table.txt staticClassExample has the namespace BasicArithmatic.main

**Comment by zcmoore** [comment]
the "namespace" was in reference to the sentence directly above that:
"BasicArithmatic.java fails to compile, as the variable "staticClassExample" cannot be found in **the namespace "BasitcArithmatic_main"**"

The symbol table lists the accurate namespace, but the compilation code is searching in the wrong place, due to the issues listed in "Solution and Side Effects"

**We need to decouple the parser and the compiler, and ensure that compiler.rs does not depend on the implementation of the parser**

**Comment by MorganNesbitt** [comment]
ah, gotcha
