### ISSUE TITLE
Overloaded functions may not be detected

### ISSUE THREAD

**Issue by zcmoore** [zcmoore/plp-grinder#12]
The lookup_function() function in symbol_table is not using argument_types in it's evaluation. As such, it may detect foo(x, y) and foo(x) as a call to the same method.

**Comment by zcmoore** [comment]
Does 4eba68c0774484acfa34d98ef1e152fef6a2c17b address this issue?

**Comment by MorganNesbitt** [comment]
Yes. foo(x, y) should not be confused with foo(x) and vice-versa.

**Comment by zcmoore** [comment]
Sweet. Closing this then.
