### ISSUE TITLE
Not correctly deleting .class files generated.

### ISSUE THREAD

**Issue by MorganNesbitt** [zcmoore/plp-grinder#18]
Needs to search through src folder provided and delete the generated .class files.
Currently works off of src file names and replacing extension. Which does not account for oracle compiler changing / nested classes.

**Comment by zcmoore** [comment]
Could we just specify the output directory for the oracle compiler, and then delete the whole directory?

**Comment by MorganNesbitt** [comment]
Yes. I will add that feature tomorrow morning.
