### ISSUE TITLE
Support final method and Classes

### ISSUE THREAD

**Issue by MorganNesbitt** [zcmoore/plp-grinder#5]
Parse final method and classes correctly.

**Comment by zcmoore** [comment]
What are the implications of this, in context of Grinder? Will we be checking final semantically?

**Comment by MorganNesbitt** [comment]
Currently, even if there is no difference it wont skip the final. So it will parse incorrectly.

**Comment by zcmoore** [comment]
Ahh. Does it throw a compile exception such as "Unsupported Token final" or "Unexpected Token final"?

**Comment by MorganNesbitt** [comment]
I don't think it will have at that moment :(. It does hit one somewhere down the line though.

**Comment by zcmoore** [comment]
Oh... yikes. I'm going to change this issue to a bug.

**Comment by MorganNesbitt** [comment]
Added panic to crash on occurrences of final.

**Comment by zcmoore** [comment]
What do we need to do to "support" the final modifier?

**Comment by MorganNesbitt** [comment]
I believe we could just remove it during pre-parsing because the oracle compiler will enforce the final rules.

**Comment by zcmoore** [comment]
Well, we're checking final rules with the oracle compiler, and ignoring final tokens on the backend now.
Is there anything else we need to have in order to support the final modifier?

**Comment by MorganNesbitt** [comment]
Option a) remove it during preparsing.
Option b) skip it while parsing instead of panicking.
Either is feasible in a small amount of time.

**Comment by zcmoore** [comment]
Let's remove it during preprocessing. We don't need it after the initial compile/semantic verification.
