### ISSUE TITLE
Support static classes

### ISSUE THREAD

**Issue by MorganNesbitt** [zcmoore/plp-grinder#6]
Add static classes symbol to symbols_table

**Comment by zcmoore** [comment]
Ideally ClassStructure**.static_classes** and ClassStructure**.non_static_classes** would both be 
Vec< ClassStructure >, and come pre-parsed

**Comment by MorganNesbitt** [comment]
It already adds them to the class structure i believe

**Comment by zcmoore** [comment]
Oops. I meant to say ideally they would be **Vec< ClassStructure >**

_editing original comment to fix typo_
_Also, it looks like the contents between angle braces was being removed by GitHub or markdown..._

**Comment by MorganNesbitt** [comment]
Ohhh a Vec< Class Structure >, that will happen when parse_class becomes fully recursive

**Comment by zcmoore** [comment]
Sweet.
